language: java
sudo: true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: U3nz3SC8ISm0z4VDV78x+LDr2ssDkMizxIaaCN6bytfLWpKTabV8t2DUpn52m2w+1NJiK3eg/F699DDXtR6CiZJEQOwqfqCCKoYCcZBfP290gvrFlLBKV0S3vJXF0g2qr8i7Gq4BlqxYxPcXU3ZaxEDhA+Zsu3IYTkNfWTciyzPWxaN9/xnpU4d8VScYShcYlHzhitPnItENur8BVVeIZeqY1haY3P4VlmeY5NloSX16wh2BgQCBOlolHCVa99BWYbwlEFJY55JijfguYcCSCSHNqRna/YHpcR3F0IQ+DYxpx/mphk8VyKgmXrztHtkDoACtRRv7XGEzEeIAEMHk14G7GKUzIjTdWm89d4R5u9eyquvEgp6X2yg0pck7+p6nOCwsNGz654Kj9Gi54PHmonfhywye1tDzBTauNVYT15LW9AD2PyPWzkbUEb9Ep4BaHAnUdIPW0ZFQk1DXrTnWR0kifm6WPxNpUxHPCIepEfEWyLmbiC+4auLQopUFQ9l8NWEMi+HF4LH4R9nIHmoQva97QdiV4xgLtJKyAwNKBq9orD5gmE518MQ9e8rQx3XgrkRLNDVMo1itne/WGYaN4Tgo2mRJjgKWx/yLyLl+7XQAkqo3PvZR4njCXvxgM9F+dV4SRcGF15BMpXus5nREl/rS4So5KpyKxlja8L3/2c4=
  app: d3-demo
  on:
    repo: chrgue/d3-demo
