language: java
sudo: true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ga7zrvpPRB+GtPb1+VOhmeKLgj4y9Qg0kkkDIi+ScUTjqSToJpSleFdiUoHj9qJ594RhN+RWhttUXVD0dWyAlGuhMWIFB5VKJonBPYtPtETcYdw59Ia/FwOElwFeC6w6O0qCsKLVwjDauDDBm3Tak0aetKnQpscP7+AUm3yNyGFOJU1htxsg40jqhhBsLviaEFHpF+A5cLPaH+mkj6AwmToLiBTY1O1FuhWRcN9+BtD/cHbe8HkOoNf/YNtvn3BZJdgleK/Ix5U5QhS/jNVIbuc2NXVeEQIbZuPV+NXfFpQ8AIXKlAzr7/JVHl9czj9j+GU8yk/TJHPMYFZ2kn1psCC2JdspURS+oWrgtotbUzurFDtMRJnS9gOr4Nhs/eHLf+Vpm0B4CDZFy5w+yUJkX8MEQWnK14HEu7QqnSSdHrFmOw9ljug0bdA2sMURHQ4+dAZMRJ9TNYCjftLzcj8KYNnCLjtPKdN/kjLHNNX/Yvw9/vV4KdqyER7p7RhXQ7zOgynuGoYCNK8XEPFqmy0RPNWa43hpa+HiABBX4r0icyMyQ26k4Y4miv4/EOIrfFuv9OuQnD1FO7tpGIWVCql+7l8bHJcw/Jus9KHYAuFCtR5tZHXoUGYYam6irIPqqy9fQsysvZn3Qe/6eiKV0nXA/a9E5ShuDnhKcahu0/Otqpc=
  app: d3-demo-app
  on:
    repo: chrgue/d3-demo
